// <copyright file="timestamp_resolution.h" company="Visualisierungsinstitut der Universität Stuttgart">
// Copyright © 2021 Visualisierungsinstitut der Universität Stuttgart. Alle Rechte vorbehalten.
// </copyright>
// <author>Christoph Müller</author>

#pragma once


namespace visus {
namespace power_overwhelming {

    /// <summary>
    /// Specifies the resolution of the timestamps generated by the library.
    /// </summary>
    enum class timestamp_resolution {

        seconds,

        milliseconds,

        nanoseconds
    };

} /* namespace power_overwhelming */
} /* namespace visus */
