#
# azure-pipelines.yml
#
# Copyright © 2023 Visualisierungsinstitut der Universität Stuttgart. Alle Rechte vorbehalten.
#

trigger:
- master

pr:
- master

schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'windows-2022'

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  generator: 'Visual Studio 17 2022'

steps:
- task: NuGetToolInstaller@0

- task: CMake@1
  displayName: 'CMake'
  inputs:
    workingDirectory: '_build'
    cmakeArgs: .. -G"$(generator)" -A"$(buildPlatform)"

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '_build/*.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
