// <copyright file="timestamp_resolution.h" company="Visualisierungsinstitut der Universität Stuttgart">
// Copyright © 2021 - 2023 Visualisierungsinstitut der Universität Stuttgart. Alle Rechte vorbehalten.
// </copyright>
// <author>Christoph Müller</author>

#pragma once


namespace visus {
namespace power_overwhelming {

    /// <summary>
    /// Specifies the resolution of the timestamps generated by the library.
    /// </summary>
    enum class timestamp_resolution {

        /// <summary>
        /// Timestamp is specified in seconds.
        /// </summary>
        seconds,

        /// <summary>
        /// Timestamp is specified in milliseconds (1/1000th of a second).
        /// </summary>
        milliseconds,

        /// <summary>
        /// Timestamp is specified in microsecond (Millionth of a second).
        /// </summary>
        microseconds,

        /// <summary>
        /// Timestamp is specified in units of hundred nanoseconds (the native
        /// quantity of many Windows APIs).
        /// </summary>
        hundred_nanoseconds,

    };

} /* namespace power_overwhelming */
} /* namespace visus */
